name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Adjust this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.11.1" # Adjust this to the Node.js version your project uses

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload artifact for deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: .next # Ensure this is the correct path to your build output directory
          name: github-pages

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions: # Add this section to set the required permissions
      id-token: write
      contents: read
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          artifact_name: github-pages
