name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Adjust this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.11.1" # Adjust this to the Node.js version your project uses

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Move build files
        run: mv .next out # Rename .next to out for consistency with deployment steps

      - name: List files in out directory
        run: ls -la out

      - name: Upload artifact for deployment
        id: upload-pages-artifact # Add an ID to the step to capture its output
        uses: actions/upload-pages-artifact@v3
        with:
          path: out # Ensure this is the correct path to your build output directory
          name: github-pages # Specify the name of the artifact

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          artifact_id: ${{ steps.upload-pages-artifact.outputs.artifact_id }} # Use the artifact ID captured from the upload step
